### ISSUE TITLE
Passing a parameter value as JSON to an OpenWhisk action makes it appear as [object Object]

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-universal#10]
In [Working with parameters](https://github.com/apache/openwhisk/blob/master/docs/parameters.md) it is shown that one can invoke an OpenWhisk action and pass JSON as parameter directly:
```
wsk action invoke --result hello -p person '{"name": "Dorothy", "place": "Kansas"}'
```
Passing this to a universal action ends up with a wrong parameter value:
```
person: [object Object]
```
Reason is: https://github.com/adobe/helix-universal/blob/20e63a4696c6f3a83071eaba9e49a74f7d5db29d/src/openwhisk-adapter.js#L65-L71

where parameters are added as search parameters to the request URL regardless of their type.

A concrete example where this is used is in `helix-index-files`, where an observation message is passed via trigger as a JSON object to the action.

**Comment by tripodsan** [comment]
obviously, only strings can be passed as params.

how do you invoke the universal action? you can't invoke the openwhisk action directly, nor use the openwhisk client.

**Comment by dominique-pfister** [comment]
> obviously, only strings can be passed as params.

The JSON is passed in the request body, not in the query string.

> how do you invoke the universal action? you can't invoke the openwhisk action directly, nor use the openwhisk client.

Is that a joke? Why not? 

Making the `wsk action invoke` call verbose, I can see that it is actually a POST, but the OpenWhiskAdapter fails to see that, and tells me it's a GET, so that seems to be the issue.

**Comment by tripodsan** [comment]
> Tell me: if I have an action that is invoked with a JSON object as payload - which is clearly supported by OpenWhisk - how do I invoke the respective universal action?

once a service is 'universal' it must use the `resolver` to obtain a url for invoking other services, for example:

https://github.com/adobe/helix-content-proxy/blob/365963163e442116677667a1a7c5ab304bba6e3f/src/onedrive-json.js#L46-L50

since the request could be routed to any environment, there is no support for features that only exists in certain targets.
hence, sending a JSON payload that automatically transforms into parameters cannot be done.

I suggest you solve this with a generic solution, either do a JSON serialization of the data and pass it as request param, or, probably better, send a POST request with the json payload.

**Comment by tripodsan** [comment]
once released, you can use the body-data middleware wrapper: https://github.com/adobe/helix-shared/pull/492
